apiVersion: apps/v1
kind: Deployment
metadata:
  ### can change this name 
  name: grean-seminar
  ###
  ### For labels need to be the same all in this file.
  labels:
    app: grean-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grean-tomcat
  template:
    metadata:
      labels:
        app: grean-tomcat
    spec:
      containers:
      - name: grean-seminar
        ### Change image here
        image: tomcat
        ### 
        ports:
        - containerPort: 8080
          name: tomcat-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"