apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop3
  labels:
    app: workshop3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop3
  template:
    metadata:
      labels:
        app: workshop3
    spec:
      containers:
      - name: workshop3
        image: asia.gcr.io/workshop-mfec/workshop3:v1
        # env:
        #   - name: DB
        #     valueFrom:
        #       secretKeyRef:
        #         name: workshop3
        #         key: db
        #   - name: APIKEY
        #     valueFrom:
        #       secretKeyRef:
        #         name: workshop3
        #         key: apikey
        ports:
        - containerPort: 8080
          name: workshop3-app
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"