kind: Service
apiVersion: v1
metadata:
  name: workshop3-stateful
spec:
  selector:
    app: workshop3-stateful
  ports:
  - protocol: TCP
    port: 80
    targetPort: workshop3-app
  type: LoadBalancer